tasks:
  - init: |
      echo "Wait for the installation"
      flutter pub get
      flutter run -d web-server --no-resident
    command: >
      echo "Ready!"

ports:
  - port: 8080
    onOpen: open-preview
