tasks:
  - before: >
      source ~/.bashrc
    init: |
      echo "Wait for the installation"
      yes | sdk i java 8.0.232-open
      sdk i kotlin
      sdkmanager --update
      yes | sdkmanager --licenses
      flutter pub get
      flutter run -d web-server --no-resident
    command: >
      echo "Ready!"
